module.exports = {
  DEFAULT_PORT: 4000,
  DEFAULT_LIST_COUNT: 10,
  SAMPLE_JSON_MAX_CHARS: 120000,
  SAMPLE_JSON_MAX_DEPTH: 40,
  SAMPLE_JSON_MAX_KEYS: 2000,
  ALLOWED_METHODS: new Set(['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE']),
  PERSIST_STATE_VERSION: 5,
  MAX_WORKSPACES: 10,
  MAX_COLLECTIONS_PER_WORKSPACE: 20,
};
